CREATE TABLE PATHOLOGIES(
	ID			UUID		PRIMARY KEY		NOT NULL,
	CODE 		VARCHAR(50)	UNIQUE			NOT NULL,
	LABEL		TEXT,
	VERSION		VARCHAR(50)					NOT NULL,
	METADATA	JSON						NOT NULL
);

CREATE TABLE HOSPITALS(
	ID 		UUID 		PRIMARY KEY 	NOT NULL,
	CODE 	VARCHAR(50)	UNIQUE			NOT NULL,
	LABEL	TEXT
);

CREATE TABLE DATASETS(
	ID 				UUID 		PRIMARY KEY		NOT NULL,
	CODE 			VARCHAR(50)	UNIQUE			NOT NULL,
	LABEL			TEXT,
	HOSPITAL_ID		UUID						NOT NULL	REFERENCES	HOSPITALS(ID),
	PATHOLOGY_ID	UUID						NOT NULL	REFERENCES	PATHOLOGIES(ID)	
);

CREATE TABLE MIP_USERS(
	ID				UUID		PRIMARY KEY		NOT NULL,
	USERNAME		VARCHAR(50)	UNIQUE			NOT NULL,
	PASSWORD		TEXT						NOT NULL
);

CREATE TABLE EXPERIMENTS(
	ID				UUID		PRIMARY KEY		NOT NULL,
	CODE			VARCHAR(50)					NOT NULL,
	LABEL			TEXT,
	MIP_USER_ID		UUID						NOT NULL 	REFERENCES	MIP_USERS(ID),
	ALGORITHM_CODE	VARCHAR(50)					NOT NULL,
	INPUT_JSON		JSON						NOT NULL,
	RESULT_JSON		JSON
);